### ISSUE TITLE
Explainer contradicting the spec regarding doctype declaration

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/MapML-Proposal#15]
https://github.com/Maps4HTML/MapML-Proposal#the-textmapml-mime-type

> The proposed doctype for such a map document is **`<!doctype mapml>`**

https://maps4html.org/MapML/spec/#documents

> A MapML document is a [[MicroXML](https://maps4html.org/MapML/spec/#ref-MicroXML)] document. As such, it MUST have a single root element named &lt;mapml&gt;. It MUST NOT have a DOCTYPE declaration

**Comment by prushforth** [comment]
Yes, that's a legit discrepancy / contradiction.  The reason the discrepancy exists is that I began developing MapML from a theory that MicroXML syntax was compatible with the HTML parser. I am not / no longer certain that this is true.  

At a minimum, I think I should have put MapML content into the XHTML namespace, which seems to be used by the HTML parser internally for sorting HTML elements from other stuff; in that case it would mean that a MapML document is not/would not be a MicroXML document. It's (more) important to be compatible with the HTML parser than to be compatible with MicroXML.

However, since @zcorpan is going to review the spec/proposal from a parser implementer perspective, I hope we'll be able to resolve this issue with Simon's help.

**Comment by zcorpan** [comment]
@prushforth I'm not a member of this GitHub org yet, so I can't self-assign.

I'm planning to start working on the MapML review next week.

**Comment by prushforth** [comment]
@zcorpan I sent you an invitation.  Cheers

**Comment by Malvoz** [comment]
This should be clarified in https://github.com/Maps4HTML/MapML/issues/72. Keeping this issue open until a conclusion has been made there, as a reminder to update the text if need be.

**Comment by prushforth** [comment]
The spec has been updated to remove MicroXML references, and the intention is still to eventually support an HTML Parser-compatible `<!doctype mapml>`, so closing this as resolved, and https://github.com/Maps4HTML/MapML/issues/72 can stay open.
